### ISSUE TITLE
Fix compile errors

### ISSUE THREAD

**Issue by vifactor** [hanickadot/co_curl#2]
This include paths is probably from the author's local machine:
https://github.com/hanickadot/co_curl/blob/375c93aa156b2f51b42500a00394a1bdcade95cc/examples/return.cpp#L1
so this examle fails to compile

Also my version of compiler (gcc 11.4) is not happy with the following warning treated by default as error:
```
[..]/co_curl/include/co_curl/easy.hpp:130:33: error: declaration of ‘fnc_t& f’ shadows a parameter [-Werror=shadow]
  130 |                         fnc_t & f = *static_cast<fnc_t *>(udata);
[...]
[..]co_curl/include/co_curl/easy.hpp:180:33: error: declaration of ‘fnc_t& f’ shadows a parameter [-Werror=shadow]
  180 |                         fnc_t & f = *static_cast<fnc_t *>(udata);
```

**Comment by hanickadot** [comment]
Thanks for reporting this issue.
